"""Markdown -> PDF converter, via xhtml2pdf.

xhtml2pdf is pure Python (backed by reportlab) - no system libraries like
Cairo/Pango/GTK/wkhtmltopdf to install, so this works out of the box on
Windows, macOS, and Linux alike. The trade-off, documented in the README, is
more limited CSS support than a browser-engine-based converter; the
stylesheet below stays within what xhtml2pdf reliably supports.
"""

from __future__ import annotations

import time
from pathlib import Path

from xhtml2pdf import pisa

from ..config import ConversionOptions
from ..errors import ConversionError
from ..models import ConversionResult
from ..parser import ParsedDocument, embed_local_images_as_data_uris
from .base import BaseConverter

_PAGE_SIZES = {"A4": "A4", "Letter": "letter", "Legal": "legal"}


def _build_css(font_family: str, font_size: int, margin_mm: int, page_size: str, orientation: str) -> str:
    size = _PAGE_SIZES.get(page_size, "A4")
    landscape = " landscape" if orientation == "landscape" else ""
    return f"""
@page {{ size: {size}{landscape}; margin: {margin_mm}mm; }}
body {{ font-family: "{font_family}", Helvetica, sans-serif; font-size: {font_size}pt;
  line-height: 1.5; color: #1b1f24; }}
h1,h2,h3,h4 {{ color: #111827; margin-top: 1.2em; }}
h1 {{ font-size: {font_size + 10}pt; border-bottom: 1pt solid #d8dee4; padding-bottom: 4pt; }}
h2 {{ font-size: {font_size + 6}pt; }}
h3 {{ font-size: {font_size + 3}pt; }}
code {{ font-family: Courier, monospace; background: #f2f5f8; padding: 1pt 3pt; }}
pre {{ font-family: Courier, monospace; background: #f2f5f8; padding: 8pt;
  border: 0.5pt solid #d8dee4; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border: 0.5pt solid #999; padding: 4pt 6pt; }}
th {{ background: #f2f5f8; }}
blockquote {{ margin: 8pt 0; padding: 4pt 10pt; border-left: 3pt solid #2563eb;
  background: #f2f5f8; color: #444; }}
a {{ color: #2563eb; }}
img {{ max-width: 100%; }}
"""


class PdfConverter(BaseConverter):
    format_name = "pdf"

    def convert(self, doc: ParsedDocument, output_path: Path, options: ConversionOptions) -> ConversionResult:
        start = time.monotonic()
        opts = options.pdf
        html_body, missing_images = embed_local_images_as_data_uris(doc.html_body, doc.source_dir)

        title_page = f"<h1>{doc.title}</h1><p style='color:#888'>Generated by Markdown Converter</p><div style='page-break-after: always;'></div>" if opts.include_title_page else ""
        toc = ""
        if opts.include_toc:
            headings = doc.soup.find_all(["h1", "h2", "h3"])
            if headings:
                items = "".join(f"<li>{h.get_text(strip=True)}</li>" for h in headings)
                toc = f"<h2>Table of Contents</h2><ul>{items}</ul><div style='page-break-after: always;'></div>"

        css = _build_css(opts.font_family, opts.font_size, opts.margin_mm, opts.page_size, opts.orientation)
        full_html = f"<html><head><style>{css}</style></head><body>{title_page}{toc}{html_body}</body></html>"

        try:
            with output_path.open("wb") as handle:
                result = pisa.CreatePDF(full_html, dest=handle)
        except Exception as exc:  # noqa: BLE001 - xhtml2pdf can raise various internal errors
            raise ConversionError(f"PDF generation failed: {exc}") from exc

        if result.err:
            raise ConversionError(
                "PDF generation reported errors.",
                details=f"xhtml2pdf error code: {result.err}",
            )

        warnings = [f"Image not found: {src}" for src in missing_images]
        return ConversionResult(
            source_path=str(doc.source_dir), output_path=str(output_path), format="pdf",
            success=True, message="PDF created successfully.", warnings=warnings,
            duration_seconds=round(time.monotonic() - start, 3),
        )
